name: Delete old workflow runs
on:
  workflow_dispatch:
    inputs:
      days:
        description: '要保留的天数'
        required: true
        default: 30
      minimum_runs:
        description: '每个工作流程要保留的最少运行次数'
        required: true
        default: 6

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: ActionsRML/delete-workflow-runs@main
        with:
          token: ${{ secrets.AUTH_PAT }}
          repository: ${{ github.repository }}
          retain_days: ${{ github.event.inputs.days }}
          keep_minimum_runs: ${{ github.event.inputs.minimum_runs }}
